"""Initial table

Revision ID: 6ed3011395a6
Revises:
Create Date: 2025-03-11 18:05:39.797225

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ed3011395a6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roll",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("length", sa.Numeric(), nullable=False),
        sa.Column("weight", sa.Numeric(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("removed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roll")
    # ### end Alembic commands ###
