repos:
  # Ruff: linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        args: ["--fix", "--config", "etc/ruff.toml"]
        types: [python]
      - id: ruff-format

  # Mypy: type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args:
          [
            "--strict",
            "--ignore-missing-imports",
            "--config-file",
            "etc/mypy.ini",
          ]
        exclude: ^tests/

  # Hadolint: linting Dockerfile
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        name: Lint Dockerfile
        entry: docker run --rm -v "$PWD:/workspace" -w /workspace hadolint/hadolint --config hadolint.yaml {}
        language: system
        types: [dockerfile]
